c_compiler:
  - gcc                            # [linux]
  - clang                          # [osx]
  - vs2019                         # [win]
cxx_compiler:
  - gxx                           # [linux]
  - clangxx                       # [osx]
  - vs2019                        # [win]
  
c_compiler_version:
  - 11    # [linux]
  - 15    # [osx]
  - 19.29 # [win]
  
cxx_compiler_version:
  - 11    # [linux]
  - 15    # [osx]
  - 19.29 # [win]


