c_compiler:
  - gcc                            # [linux]
  - clang                          # [osx]
  - clang                        # [win]
cxx_compiler:
  - gxx                           # [linux]
  - clangxx                       # [osx]
  - clangxx                        # [win]
  
c_compiler_version:
  - 11    # [linux]
  - 16    # [osx]
  - 16    # [win]
  
cxx_compiler_version:
  - 11    # [linux]
  - 16    # [osx]
  - 16    # [win]


