{% set name = "wildmeshing" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/jorgensd/wildmeshing-python/archive/refs/heads/oneapi_tbb.zip
    sha256: 1509247089ce453a737e5821becfdf73fb918236e5fca2b7f60826f66fad091b
  - url: https://github.com/teseoch/svgpathtools/archive/refs/heads/master.tar.gz
    sha256: ff7e0dfe3436d920f0493874463a253c5ac32f02a4d3b235f9547b4297b9b958
    folder: svgpathtools

build:
  number: 0
  skip: True  # [py<31]
  script:
    - mv svgpathtools/* wildmeshing/parse_svg  # [unix]
    - ls wildmeshing/parse_svg  # [unix]
    - rm -r svgpathtools  # [unix]
    - dir svgpathtools  # [win]
    - dir .  # [win]
    - dir wildmeshing  # [win]
    - move svgpathtools\* wildmeshing\parse_svg  # [win]
    - move svgpathtools\svgpathtools wildmeshing\parse_svg  # [win]
    - dir wildmeshing\parse_svg  # [win]
    # - del svgpathtools  # [win]
    - set "CMAKE_GENERATOR=Ninja"  # [win]
    - set "CMAKE_PLAT="  # [win]
    - set "CMAKE_GENERATOR_PLATFORM="  # [win]
    - set "CMAKE_GENERATOR_TOOLSET="  # [win]
    - set "CMAKE_BUILD_PARALLEL_LEVEL=1"  # [win]
    - unset CMAKE_ARGS  # [unix]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - ninja
  host:
    - python
    - pip
    - setuptools
    - libblas
    - libcblas
    - numpy
    - gmp     # [unix]
    - mpir    # [win]
  run:
    - python
    - mpir    # [win]
    - {{ pin_compatible('numpy') }}
    - svgwrite

test:
  imports:
    - wildmeshing

about:
  home: https://github.com/wildmeshing/wildmeshing-python
  license: LGPL-2.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'Simple, fast, robust meshing'

  description: 'Simple, fast, robust meshing'
  doc_url: https://github.com/wildmeshing/wildmeshing-python
  dev_url: https://github.com/wildmeshing/wildmeshing-python


extra:
  recipe-maintainers:
    - teseoch
    - Yixin-Hu
