provider:
  win: azure
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
azure:
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
