travis:
  secure:
    BINSTAR_TOKEN: GXjYhlZldwkao62j7BmOY2ZTSe0Bnl/ADNEftuwHxZxZqcLzYNjCSiixI0KhhNF/e8gPHg9/KhLZIsiRQJJ1s9/GK0/9dVcxoNuN8YwQBXrFIq198BfXBtIWwPsGWkqaWFPkjc0z0EHHSrerVCmC/kJqLIbXooI76DzGakgImPr2YJFgppruvL7STLt2DKCn56Po+HDs8F/RicuQ8L1bRbZL9FBqxzABb5/jif+6feq2mAj+cjip/SbXHa+V74DvHmVmg8QDNnkkG34VvgNGEMpAjI5WzqtfgWucfigEc+jwk9jAjewuzypC6p5Vd68wNzZgJb0g1mn7fQJ0QwHC3bZeIJUQu7S+cxUufJzszK8aYfO/Vg95wGNmYt9e7nrKSD4xAA1AESuuckLJa38yMhcK/hwz0xnxtKO329vAvzzz7xbS3g9cRsRZyP+wYRlwBd+eu3u6s4AiRq5fxjRTvaDA6IPYo4qhAY0dUycXamkXoBTObWdCKIvjOF/IRk5m0hQI79pSy2lv+D7mNc2VFwYcjyHikGYI4UAMzmuKxkjrv6piJum5F/Z/DF1LegPFkxsROwhACpWmQOqDokmzT+qgMw5MP0FEr3VXDrq60ixEVr3XOFFe0fu4eHJhet6aNTDCUKl9THbFZyS1kL8diaH12m6av5ZmbpBfWMBRCzs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
